<?php

$rcmail_config['GKconfig'] =  array(
    'email' => "gesiel.bernardes@gmail.com",   /* Admin e-mail */
    'agentid' => "ed7a8553da1d467d670b28a43c1fe72d0409948eb2193c12e50db3a3623349f6",  /* ID for the agent (your system) */
    'key' => "CFNn6hMvvtTefubmMvQVpstE1iJAgdI07MoXVTmPUI4=",     /* Key in B64 to communicate with GuardianKey */
    'iv' => "JSR5E6Leuv3gX12dbQbdcw==",      /* IV in B64 for the key */
    'service' => "Roundcube",      /* Your service name*/
    'orgid' => "161d5470619ab52c61c1ed212dd52c1ca0e8a219b6d9d413c44cb9f90dae70cc",   /* Your Org identification in GuardianKey */
    'authgroupid' => "ed7a8553da1d467d670b28a43c1fe72d0409948eb2193c12e50db3a3623349f6", /* A Authentication Group identification, generated by GuardianKey */
    'reverse' => "True", /* If you will locally perform a reverse DNS resolution */
	'api_url' => "https://api.guardiankey.io",
);
